[package]
name = "punge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[lib]
#name = "punge"
#crate-type = ["cdylib"]

[dependencies]
rusqlite = { version = "0.27.0", features = ["bundled", "chrono"] }
pyo3 = { version = "0.17.3", features = ["extension-module", "auto-initialize"] }
regex = "1.7.0"
# this version is needed to get around the youtube limiting problem :)
rustube = { git = "https://github.com/Discursif/rustube", features = ["blocking"]}
reqwest = {features = ["blocking"], version = "0.11.13"}
serde_json = "1.0.89"
itertools = "0.10.5"
chrono = "0.4.24"
thiserror = "1.0"
uuid = {features = ["v4"], version = "1.3.1" }
