[package]
name = "punge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "punge"
crate-type = ["cdylib"]

[dependencies]
rusqlite = { version = "0.27.0", features = ["bundled"] }
pyo3 = { version = "0.17.3", features = ["extension-module"] }