# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Projects\Python Projects\punge\venv\Lib\site-packages\QtDesigner\punge_gui_exp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1235, 780)
        MainWindow.setStyleSheet("background-color: rgb(27, 27, 28)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1235, 780))
        self.centralwidget.setMaximumSize(QtCore.QSize(1235, 780))
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, -30, 1071, 691))
        self.stackedWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setLineWidth(10)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setAutoFillBackground(False)
        self.main_page.setStyleSheet("background-color: rgb(39, 44, 52)")
        self.main_page.setObjectName("main_page")
        self.content_frame_1 = QtWidgets.QFrame(self.main_page)
        self.content_frame_1.setGeometry(QtCore.QRect(160, 110, 240, 140))
        self.content_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame_1.setObjectName("content_frame_1")
        self.content_frame_2 = QtWidgets.QFrame(self.main_page)
        self.content_frame_2.setGeometry(QtCore.QRect(160, 300, 240, 140))
        self.content_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame_2.setObjectName("content_frame_2")
        self.content_frame_3 = QtWidgets.QFrame(self.main_page)
        self.content_frame_3.setGeometry(QtCore.QRect(160, 490, 240, 140))
        self.content_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame_3.setObjectName("content_frame_3")
        self.content_frame_large = QtWidgets.QFrame(self.main_page)
        self.content_frame_large.setGeometry(QtCore.QRect(710, 110, 240, 520))
        self.content_frame_large.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame_large.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame_large.setObjectName("content_frame_large")
        self.stackedWidget.addWidget(self.main_page)
        self.download_music_page = QtWidgets.QWidget()
        self.download_music_page.setStyleSheet("background-color: rgb(39, 44, 52)")
        self.download_music_page.setObjectName("download_music_page")
        self.textEdit = QtWidgets.QTextEdit(self.download_music_page)
        self.textEdit.setGeometry(QtCore.QRect(400, 80, 400, 50))
        self.textEdit.setObjectName("textEdit")
        self.swap_between_insta_yt_button = QtWidgets.QPushButton(self.download_music_page)
        self.swap_between_insta_yt_button.setGeometry(QtCore.QRect(30, 50, 171, 71))
        self.swap_between_insta_yt_button.setObjectName("swap_between_insta_yt_button")
        self.clear_link_button = QtWidgets.QPushButton(self.download_music_page)
        self.clear_link_button.setGeometry(QtCore.QRect(800, 80, 75, 51))
        self.clear_link_button.setObjectName("clear_link_button")
        self.download_link_button = QtWidgets.QPushButton(self.download_music_page)
        self.download_link_button.setGeometry(QtCore.QRect(420, 130, 361, 41))
        self.download_link_button.setObjectName("download_link_button")
        self.stackedWidget.addWidget(self.download_music_page)
        self.youtube_downloader_page = QtWidgets.QWidget()
        self.youtube_downloader_page.setAutoFillBackground(False)
        self.youtube_downloader_page.setStyleSheet("background-color: rgb(39, 44, 52)")
        self.youtube_downloader_page.setObjectName("youtube_downloader_page")
        self.label = QtWidgets.QLabel(self.youtube_downloader_page)
        self.label.setGeometry(QtCore.QRect(490, 220, 201, 131))
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.youtube_downloader_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setStyleSheet("background-color: rgb(39, 44, 52)")
        self.settings_page.setObjectName("settings_page")
        self.setting_scroll_area = QtWidgets.QScrollArea(self.settings_page)
        self.setting_scroll_area.setGeometry(QtCore.QRect(9, 29, 1071, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_scroll_area.sizePolicy().hasHeightForWidth())
        self.setting_scroll_area.setSizePolicy(sizePolicy)
        self.setting_scroll_area.setStyleSheet("QscrollArea {\n"
"    border: none;\n"
"}\n"
"QScrollArea QWidget {\n"
"qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.setting_scroll_area.setWidgetResizable(True)
        self.setting_scroll_area.setObjectName("setting_scroll_area")
        self.scroll_area_container = QtWidgets.QWidget()
        self.scroll_area_container.setEnabled(True)
        self.scroll_area_container.setGeometry(QtCore.QRect(0, 0, 1069, 679))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_container.sizePolicy().hasHeightForWidth())
        self.scroll_area_container.setSizePolicy(sizePolicy)
        self.scroll_area_container.setMinimumSize(QtCore.QSize(1, 1))
        self.scroll_area_container.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scroll_area_container.setStyleSheet("border: none;")
        self.scroll_area_container.setObjectName("scroll_area_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scroll_area_container)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settings_label = QtWidgets.QLabel(self.scroll_area_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_label.sizePolicy().hasHeightForWidth())
        self.settings_label.setSizePolicy(sizePolicy)
        self.settings_label.setStyleSheet("QLabel {\n"
"    font-size: 50px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border-bottom: 2px solid #FFFFFF;\n"
"    text-align: center;\n"
"    text-shadow: 2px;\n"
"\n"
"}")
        self.settings_label.setObjectName("settings_label")
        self.verticalLayout_3.addWidget(self.settings_label)
        self.change_download_location_frame = QtWidgets.QFrame(self.scroll_area_container)
        self.change_download_location_frame.setStyleSheet("border: 10px;")
        self.change_download_location_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.change_download_location_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.change_download_location_frame.setObjectName("change_download_location_frame")
        self.change_download_location_label = QtWidgets.QLabel(self.change_download_location_frame)
        self.change_download_location_label.setGeometry(QtCore.QRect(70, 20, 241, 71))
        self.change_download_location_label.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: #aba9a9;\n"
"    padding: 10px;\n"
"    text-align: center;\n"
"    text-shadow: 2px;\n"
"\n"
"}")
        self.change_download_location_label.setObjectName("change_download_location_label")
        self.frame = QtWidgets.QFrame(self.change_download_location_frame)
        self.frame.setGeometry(QtCore.QRect(100, 70, 540, 90))
        self.frame.setStyleSheet("QFrame {\n"
"border: 3px solid #969393;\n"
"border-radius: 8px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 20, 371, 20))
        self.lineEdit.setStyleSheet("background-color: #303030;\n"
"color: white;")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.label_2.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: #aba9a9;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.label_3.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: #aba9a9;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 50, 371, 20))
        self.lineEdit_2.setStyleSheet("background-color: #303030;\n"
"color: white;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.audio_folder_button = QtWidgets.QPushButton(self.frame)
        self.audio_folder_button.setGeometry(QtCore.QRect(460, 20, 30, 20))
        self.audio_folder_button.setStyleSheet("QPushButton {\n"
"border: none;\n"
"background-image: url(:/newPrefix/folder small.png);\n"
"border-style: sunken;\n"
" background-origin: content;\n"
"background-size: contain;\n"
"}")
        self.audio_folder_button.setText("")
        self.audio_folder_button.setObjectName("audio_folder_button")
        self.thumbnail_button = QtWidgets.QPushButton(self.frame)
        self.thumbnail_button.setGeometry(QtCore.QRect(460, 50, 30, 20))
        self.thumbnail_button.setStyleSheet("QPushButton {\n"
"border: none;\n"
"background-image: url(:/newPrefix/folder small.png);\n"
"border-style: sunken;\n"
" background-origin: content;\n"
"background-size: contain;\n"
"}")
        self.thumbnail_button.setText("")
        self.thumbnail_button.setObjectName("thumbnail_button")
        self.frame_2 = QtWidgets.QFrame(self.change_download_location_frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 270, 1051, 500))
        self.frame_2.setMinimumSize(QtCore.QSize(500, 500))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(100, 90, 150, 90))
        self.frame_3.setStyleSheet("QFrame {\n"
"border: 3px solid #969393;\n"
"border-radius: 8px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox.setGeometry(QtCore.QRect(80, 30, 62, 22))
        self.doubleSpinBox.setStyleSheet("QDoubleSpinBox {\n"
"background-color: #303030;\n"
"color: white;\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(10, 35, 47, 13))
        self.label_8.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: #aba9a9;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(80, 40, 271, 61))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    color: #aba9a9;\n"
"    padding: 10px;\n"
"    text-align: center;\n"
"    text-shadow: 2px;\n"
"\n"
"}")
        self.label_6.setObjectName("label_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(280, 90, 150, 90))
        self.frame_4.setStyleSheet("QFrame {\n"
"border: 3px solid #969393;\n"
"border-radius: 8px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(80, 30, 62, 22))
        self.doubleSpinBox_4.setStyleSheet("QDoubleSpinBox {\n"
"background-color: #303030;\n"
"color: white;\n"
"border: 2px solid black;\n"
"}\n"
"\n"
"\n"
"")
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(10, 35, 47, 13))
        self.label_9.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: #aba9a9;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.label_6.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.verticalLayout_3.addWidget(self.change_download_location_frame)
        self.setting_scroll_area.setWidget(self.scroll_area_container)
        self.stackedWidget.addWidget(self.settings_page)
        self.right_frame = QtWidgets.QFrame(self.centralwidget)
        self.right_frame.setGeometry(QtCore.QRect(1060, 0, 180, 660))
        self.right_frame.setStyleSheet("background-color: rgb(38, 38, 38)")
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.menuframe = QtWidgets.QFrame(self.right_frame)
        self.menuframe.setGeometry(QtCore.QRect(0, 0, 180, 200))
        self.menuframe.setStyleSheet("background-color: rgb(38, 38, 38)")
        self.menuframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuframe.setObjectName("menuframe")
        self.settings_menu_button = QtWidgets.QPushButton(self.menuframe)
        self.settings_menu_button.setGeometry(QtCore.QRect(0, 150, 180, 50))
        self.settings_menu_button.setStyleSheet("color: rgb(148, 148, 148)")
        self.settings_menu_button.setObjectName("settings_menu_button")
        self.youtube_dl_menu_button = QtWidgets.QPushButton(self.menuframe)
        self.youtube_dl_menu_button.setGeometry(QtCore.QRect(0, 100, 180, 50))
        self.youtube_dl_menu_button.setStyleSheet("color: rgb(148, 148, 148)")
        self.youtube_dl_menu_button.setObjectName("youtube_dl_menu_button")
        self.download_music_menu_button = QtWidgets.QPushButton(self.menuframe)
        self.download_music_menu_button.setGeometry(QtCore.QRect(0, 50, 180, 50))
        self.download_music_menu_button.setStyleSheet("color: rgb(148, 148, 148)")
        self.download_music_menu_button.setObjectName("download_music_menu_button")
        self.home_button = QtWidgets.QPushButton(self.menuframe)
        self.home_button.setGeometry(QtCore.QRect(0, 0, 180, 50))
        self.home_button.setStyleSheet("color: rgb(148, 148, 148)")
        self.home_button.setObjectName("home_button")
        self.playlist_scroll_area = QtWidgets.QScrollArea(self.right_frame)
        self.playlist_scroll_area.setGeometry(QtCore.QRect(0, 215, 180, 445))
        self.playlist_scroll_area.setMinimumSize(QtCore.QSize(0, 100))
        self.playlist_scroll_area.setStyleSheet("QScrollArea {\n"
"border: 0px\n"
"}\n"
"\n"
"QScrollBar {\n"
"height: 0px;\n"
"width: 0px;\n"
"}")
        self.playlist_scroll_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.playlist_scroll_area.setLineWidth(0)
        self.playlist_scroll_area.setWidgetResizable(True)
        self.playlist_scroll_area.setObjectName("playlist_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 180, 445))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.playlist_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.menu_playlist_divider = QtWidgets.QFrame(self.right_frame)
        self.menu_playlist_divider.setGeometry(QtCore.QRect(0, 200, 180, 20))
        self.menu_playlist_divider.setStyleSheet("color: #2D334E")
        self.menu_playlist_divider.setFrameShadow(QtWidgets.QFrame.Plain)
        self.menu_playlist_divider.setLineWidth(2)
        self.menu_playlist_divider.setMidLineWidth(0)
        self.menu_playlist_divider.setFrameShape(QtWidgets.QFrame.HLine)
        self.menu_playlist_divider.setObjectName("menu_playlist_divider")
        self.play_pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_pause_button.setGeometry(QtCore.QRect(565, 675, 50, 50))
        self.play_pause_button.setAutoFillBackground(False)
        self.play_pause_button.setStyleSheet("border-image: url(:/newPrefix/img/punge_play_new.png)")
        self.play_pause_button.setText("")
        self.play_pause_button.setFlat(True)
        self.play_pause_button.setObjectName("play_pause_button")
        self.left_skip_button = QtWidgets.QPushButton(self.centralwidget)
        self.left_skip_button.setGeometry(QtCore.QRect(425, 675, 110, 50))
        self.left_skip_button.setStyleSheet("QPushButton {\n"
"border: none;\n"
"background-image: url(:/newPrefix/img/punge_left_new.png);\n"
"border-style: sunken;\n"
" background-origin: content;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-top: 4px;\n"
"    padding-bottom: 0px;\n"
"}")
        self.left_skip_button.setText("")
        self.left_skip_button.setObjectName("left_skip_button")
        self.right_skip_button = QtWidgets.QPushButton(self.centralwidget)
        self.right_skip_button.setGeometry(QtCore.QRect(645, 675, 110, 50))
        self.right_skip_button.setStyleSheet("QPushButton {\n"
"border: none;\n"
"background-image: url(:/newPrefix/img/punge_right_new.png);\n"
"border-style: sunken;\n"
" background-origin: content;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-top: 4px;\n"
"    padding-bottom: 0px;\n"
"}")
        self.right_skip_button.setText("")
        self.right_skip_button.setObjectName("right_skip_button")
        self.shuffle_button = QtWidgets.QPushButton(self.centralwidget)
        self.shuffle_button.setGeometry(QtCore.QRect(910, 690, 45, 45))
        self.shuffle_button.setStyleSheet("QPushButton {\n"
"border-image: url(:/newPrefix/img/shuffle_off_new.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center center;\n"
"    padding: 0;\n"
"    border: none;\n"
"}\n"
"QPushButton::checked {\n"
"border-image: url(:/newPrefix/img/shuffle_on_new.png);\n"
"}\n"
"QPushButton::indicator {\n"
"image: none;\n"
"}")
        self.shuffle_button.setText("")
        self.shuffle_button.setObjectName("shuffle_button")
        self.album_button = QtWidgets.QPushButton(self.centralwidget)
        self.album_button.setGeometry(QtCore.QRect(990, 690, 45, 45))
        self.album_button.setStyleSheet("border-image: url(:/newPrefix/img/defined background.png)")
        self.album_button.setText("")
        self.album_button.setObjectName("album_button")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 670, 241, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.song_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.song_label.setStyleSheet("color: white")
        self.song_label.setObjectName("song_label")
        self.verticalLayout.addWidget(self.song_label)
        self.artist_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.artist_label.setStyleSheet("color: white")
        self.artist_label.setObjectName("artist_label")
        self.verticalLayout.addWidget(self.artist_label)
        self.cover_frame = QtWidgets.QFrame(self.centralwidget)
        self.cover_frame.setGeometry(QtCore.QRect(30, 670, 100, 100))
        self.cover_frame.setStyleSheet("border-image: url(:/newPrefix/img/palceholder_bg.jpg)")
        self.cover_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cover_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cover_frame.setObjectName("cover_frame")
        self.media_scrubber_slider = QtWidgets.QSlider(self.centralwidget)
        self.media_scrubber_slider.setGeometry(QtCore.QRect(320, 750, 540, 22))
        self.media_scrubber_slider.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.media_scrubber_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #999999;\n"
"height: 9px;\n"
"\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 30px;\n"
"    image: url(:/newPrefix/img/scrubbing_cursor-01.png);\n"
"    margin: -9px -9px;\n"
"    height: -30px;\n"
"}\n"
"\n"
"QSlider::add-page {\n"
"background: #595959;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"}\n"
"\n"
"QSlider::sub-page {\n"
"background: #331DB3;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"}")
        self.media_scrubber_slider.setOrientation(QtCore.Qt.Horizontal)
        self.media_scrubber_slider.setObjectName("media_scrubber_slider")
        self.beginning_time_label = QtWidgets.QLabel(self.centralwidget)
        self.beginning_time_label.setGeometry(QtCore.QRect(280, 750, 31, 16))
        self.beginning_time_label.setStyleSheet("color:white")
        self.beginning_time_label.setObjectName("beginning_time_label")
        self.volume_slider = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider.setGeometry(QtCore.QRect(1060, 700, 160, 22))
        self.volume_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #999999;\n"
"height: 9px;\n"
"\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 30px;\n"
"    image: url(:/newPrefix/img/scrubbing_cursor-01.png);\n"
"    margin: -9px -9px;\n"
"    height: -30px;\n"
"}\n"
"\n"
"QSlider::add-page {\n"
"background: #595959;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"}\n"
"\n"
"QSlider::sub-page {\n"
"background: #A8A8A8;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"}")
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.end_time_label = QtWidgets.QLabel(self.centralwidget)
        self.end_time_label.setGeometry(QtCore.QRect(870, 760, 47, 13))
        self.end_time_label.setStyleSheet("color: white\n"
"")
        self.end_time_label.setObjectName("end_time_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.swap_between_insta_yt_button.setText(_translate("MainWindow", "Swap between instagram / youtube"))
        self.clear_link_button.setText(_translate("MainWindow", "X (close)"))
        self.download_link_button.setText(_translate("MainWindow", "Download!"))
        self.label.setText(_translate("MainWindow", "youtube downloader pagel"))
        self.settings_label.setText(_translate("MainWindow", "Settings"))
        self.change_download_location_label.setText(_translate("MainWindow", "Change Download Locations"))
        self.label_2.setText(_translate("MainWindow", "Audio"))
        self.label_3.setText(_translate("MainWindow", "Thumbnails"))
        self.label_8.setText(_translate("MainWindow", "Increase"))
        self.label_6.setText(_translate("MainWindow", "Change Bind Volume Increments"))
        self.label_9.setText(_translate("MainWindow", "Decrease"))
        self.settings_menu_button.setText(_translate("MainWindow", "Settings"))
        self.youtube_dl_menu_button.setText(_translate("MainWindow", "YouTube Downloader"))
        self.download_music_menu_button.setText(_translate("MainWindow", "Download Music"))
        self.home_button.setText(_translate("MainWindow", "Home"))
        self.song_label.setText(_translate("MainWindow", "Otis"))
        self.artist_label.setText(_translate("MainWindow", "Kanye West"))
        self.beginning_time_label.setText(_translate("MainWindow", "0:00"))
        self.end_time_label.setText(_translate("MainWindow", "5:00"))

import resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
